baseURL = "https://sainthillier.fr"
languageCode = "fr-FR"
title = "Guillaume Sainthillier"
googleAnalytics = "UA-44318869-1"
assetDir = "static"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[imaging]
  resampleFilter = "Linear"

[params.social]
  github = "https://github.com/guillaume-sainthillier"
  linkedin = "https://www.linkedin.com/in/developpeur-web-toulouse/"
