[build]
publish = "public"
command = "yarn run build:hugo"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/cgv"
  to = "/conditions-generales-de-vente"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/build/*"
  [headers.values]
	cache-control = '''
	max-age=31536000,
	public,
	immutable'''
