imports:
    - { resource: parameters.yml }
    - { resource: security.yml }


jms_security_extra:
    expressions: ~

framework:
    esi:       { enabled: true }
    fragments: { path: /_fragment }
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    trusted_hosts:   ~

fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Guy\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    from_email:
        address:        %sender_address%
        sender_name:    Guillaume Sainthillier
    registration:
        form:
            type: guy_user_registration
    profile:
        form:
            type: guy_user_profile

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:fields.html.twig'
    globals:
        version:          "2.3"
        email:          guillaume@sainthillier.fr
        telephones:     ["06", "07", "27", "58", "26"]

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: 'java'
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
#    host:      %mailer_host%
#    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%
    sender_address:  %sender_address%
    delivery_address:  %mailer_delivery%
    
liip_imagine:
    resolvers:
       default:
            web_path: 
                web_root: %kernel.root_dir%/../web
                cache_prefix: uploads/min

    filter_sets:
        cache: ~
        thumb_icon:
            quality: 100
            filters:
                thumbnail: { size: [16, 16], mode: outbound }
        thumb_realisation:
            quality: 80
            filters:
                thumbnail: { size: [267, 200] }
        thumb_realisation_full:
            quality: 90
            filters:
                thumbnail: { size: [560, 420] }
        thumb_realisation_thumb:
            quality: 100
            filters:
                thumbnail: { size: [32, 32] }
                
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true