_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

guy_admin:
    resource: "@GuyAdminBundle/Resources/config/routing.yml"
    prefix:   /admin


guy_user:
    resource: "@GuyUserBundle/Resources/config/routing.yml"
    prefix:   /

guy_blog:
    resource: "@GuyBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"