guy_details_realisation:
    pattern: /details/{slug}
    defaults: { _controller: GuyBlogBundle:Page:detailsRealisation}
    requirements:
        nom:  (.+)
        
guy_cv:
    path:  /
    defaults: { _controller: GuyBlogBundle:Page:index}

guy_contact:
    path: /message
    defaults: { _controller: GuyBlogBundle:Page:contact}
    requirements:
        _method:  POST

guy_old_routes:
    pattern: /{old}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: guy_cv
        permanent: true # this is for 301
    requirements:
        old: (labs|contact|realisations|mentions_legales|mentions-legales|about)