parameters:
#    guy_user.example.class: Guy\UserBundle\Example

services:
    guy_user.registration.form.type:
        class: Guy\UserBundle\Form\RegisterFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: guy_user_registration }

    guy_user.profile.form.type:
        class: Guy\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: guy_user_profile }