guy_detail_realisation:
    path: /tag/{tag}
    defaults: { _controller: GuyAdminBundle:Realisation:index, nom: false}
    requirements:
        tag: .+

guy_gestion_realisation_ajouter:
    path: /ajouter
    defaults: { _controller: GuyAdminBundle:Realisation:ajouter}

guy_detail_realisation_nom:
    path: /{nom}
    defaults: { _controller: GuyAdminBundle:Realisation:index, tag: false}
    requirements:
        nom: \D+

guy_gestion_realisation_modifier:
    path: /{id}
    defaults: { _controller: GuyAdminBundle:Realisation:modifier}
    requirements:
        id: \d+

guy_gestion_realisation_supprimer:
    path: /{id}/supprimer
    defaults: { _controller: GuyAdminBundle:Realisation:supprimer}
    requirements:
        id: \d+
