guy_gestion_experience_ajouter:
    path: /ajouter
    defaults: { _controller: GuyAdminBundle:Experience:ajouter}
    
guy_gestion_experience_modifier:
    path: /{id}
    defaults: { _controller: GuyAdminBundle:Experience:modifier}
    requirements:
        id: \d+

guy_gestion_experience_supprimer:
    path: /{id}/supprimer
    defaults: { _controller: GuyAdminBundle:Experience:supprimer}
    requirements:
        id: \d+
